changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Performance Improvements
      labels:
        - performance
    - title: Dependencies
      labels:
        - dependencies
    - title: Styles
      labels:
        - style
    - title: Miscellaneous Chores
      labels:
        - chore
    - title: Code Refactoring
      labels:
        - refactoring
    - title: Tests
      labels:
        - test
    - title: Documentation
      labels:
        - documentation
    - title: Build System
      labels:
        - build
    - title: Continuous Integration
      labels:
        - ci
    - title: Other Changes
      labels:
        - "*"
