name: "mado-action"
description: "Run mado to check Markdown files"
author: "Akiomi Kamakura"
branding:
  icon: check
  color: white

inputs:
  args:
    description: "Arguments passed to Mado. Defaults to `check .`."
    required: false
    default: "check ."

runs:
  using: 'composite'
  steps:
    - id: mado
      shell: bash
      run: $GITHUB_ACTION_PATH/action/entrypoint.sh
      env:
        INSTALL_DIR: .
        INPUT_ARGS: ${{ inputs.args }}
