[lint]
output-format = "concise"
rules = [
  "MD001",
  "MD002",
  "MD003",
  "MD004",
  "MD005",
  "MD006",
  "MD007",
  "MD009",
  "MD010",
  "MD012",
  "MD013",
  "MD014",
  "MD018",
  "MD019",
  "MD022",
  "MD023",
  "MD024",
  "MD025",
  "MD026",
  "MD027",
  "MD028",
  "MD029",
]

[lint.md002]
level = 1

[lint.md003]
style = "consistent"

[lint.md004]
style = "consistent"

[lint.md007]
indent = 4

[lint.md013]
line-length = 80

[lint.md025]
level = 1
