[lint]
output-format = "concise"
rules = [
  "MD001",
  "MD002",
  "MD003",
  "MD004",
  "MD005",
  "MD006",
  "MD007",
  "MD009",
  "MD010",
  "MD012",
  "MD013",
  "MD014",
  "MD018",
  "MD019",
  "MD022",
  "MD023",
  "MD024",
  "MD025",
  "MD026",
  "MD027",
  "MD028",
  "MD029",
  "MD030",
  "MD031",
  "MD032",
  "MD033",
]

[lint.md002]
level = 1

[lint.md003]
style = "consistent"

[lint.md004]
style = "consistent"

[lint.md007]
indent = 4

[lint.md013]
line-length = 80

[lint.md025]
level = 1

[lint.md026]
punctuation = ".,;:!?"

[lint.md029]
style = "one"

[lint.md030]
ul_single = 1
ol_single = 1
ul_multi = 1
ol_multi = 1

[lint.md033]
allowed-elements = []
